// <auto-generated />
using System;
using ApartmanApp.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ApartmanApp.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ApartmanApp.Core.Entities.Aidat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Ay")
                        .HasColumnType("integer");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("integer");

                    b.Property<string>("OdemeDurumu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("OdemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Tutar")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("Yil")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.ToTable("Aidatlar");
                });

            modelBuilder.Entity("ApartmanApp.Core.Entities.Ariza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("BildirenId")
                        .HasColumnType("integer");

                    b.Property<string>("BlokNo")
                        .HasColumnType("text");

                    b.Property<int>("Durum")
                        .HasColumnType("integer");

                    b.Property<int>("Oncelik")
                        .HasColumnType("integer");

                    b.Property<string>("RedNedeni")
                        .HasColumnType("text");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BildirenId");

                    b.ToTable("Arizalar", (string)null);
                });

            modelBuilder.Entity("ApartmanApp.Core.Entities.ArizaFoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArizaId")
                        .HasColumnType("integer");

                    b.Property<string>("DosyaAdi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long>("DosyaBoyutu")
                        .HasColumnType("bigint");

                    b.Property<string>("DosyaYolu")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("YuklemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ArizaId");

                    b.ToTable("ArizaFotolar");
                });

            modelBuilder.Entity("ApartmanApp.Core.Entities.ArizaTakip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArizaId")
                        .HasColumnType("integer");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TakipTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("ArizaId", "KullaniciId")
                        .IsUnique();

                    b.ToTable("ArizaTakipler", (string)null);
                });

            modelBuilder.Entity("ApartmanApp.Core.Entities.Bildirim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AliciId")
                        .HasColumnType("integer");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("GonderimTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Icerik")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("Okundu")
                        .HasColumnType("boolean");

                    b.Property<string>("Tip")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("AliciId");

                    b.ToTable("Bildirimler");
                });

            modelBuilder.Entity("ApartmanApp.Core.Entities.Blok", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Bloklar");
                });

            modelBuilder.Entity("ApartmanApp.Core.Entities.Daire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BlokId")
                        .HasColumnType("integer");

                    b.Property<string>("DaireNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BlokId");

                    b.ToTable("Daireler");
                });

            modelBuilder.Entity("ApartmanApp.Core.Entities.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("BlokNo")
                        .HasColumnType("text");

                    b.Property<string>("DaireNo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FcmToken")
                        .HasColumnType("text");

                    b.Property<int>("Rol")
                        .HasColumnType("integer");

                    b.Property<string>("SifreHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Kullanicilar", (string)null);
                });

            modelBuilder.Entity("ApartmanApp.Core.Entities.OtomatikAidat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("integer");

                    b.Property<int?>("SonUretimAy")
                        .HasColumnType("integer");

                    b.Property<int?>("SonUretimYil")
                        .HasColumnType("integer");

                    b.Property<decimal>("Tutar")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId")
                        .IsUnique();

                    b.ToTable("OtomatikAidatlar");
                });

            modelBuilder.Entity("ApartmanApp.Core.Entities.Oylama", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("BaslangicTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("BitisTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OlusturanId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OlusturanId");

                    b.ToTable("Oylamalar", (string)null);
                });

            modelBuilder.Entity("ApartmanApp.Core.Entities.OylamaOyu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("KullaniciId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OyTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OylamaId")
                        .HasColumnType("integer");

                    b.Property<int>("SecenekId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("SecenekId");

                    b.HasIndex("OylamaId", "KullaniciId")
                        .IsUnique();

                    b.ToTable("OylamaOylari", (string)null);
                });

            modelBuilder.Entity("ApartmanApp.Core.Entities.OylamaSecenek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Metin")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("OylamaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OylamaId");

                    b.ToTable("OylamaSecenekler", (string)null);
                });

            modelBuilder.Entity("ApartmanApp.Core.Entities.Aidat", b =>
                {
                    b.HasOne("ApartmanApp.Core.Entities.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("ApartmanApp.Core.Entities.Ariza", b =>
                {
                    b.HasOne("ApartmanApp.Core.Entities.Kullanici", "Bildiren")
                        .WithMany("Arizalar")
                        .HasForeignKey("BildirenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bildiren");
                });

            modelBuilder.Entity("ApartmanApp.Core.Entities.ArizaFoto", b =>
                {
                    b.HasOne("ApartmanApp.Core.Entities.Ariza", "Ariza")
                        .WithMany("Fotograflar")
                        .HasForeignKey("ArizaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ariza");
                });

            modelBuilder.Entity("ApartmanApp.Core.Entities.ArizaTakip", b =>
                {
                    b.HasOne("ApartmanApp.Core.Entities.Ariza", "Ariza")
                        .WithMany("Takipler")
                        .HasForeignKey("ArizaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApartmanApp.Core.Entities.Kullanici", "Kullanici")
                        .WithMany("Takipler")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ariza");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("ApartmanApp.Core.Entities.Bildirim", b =>
                {
                    b.HasOne("ApartmanApp.Core.Entities.Kullanici", "Alici")
                        .WithMany()
                        .HasForeignKey("AliciId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Alici");
                });

            modelBuilder.Entity("ApartmanApp.Core.Entities.Daire", b =>
                {
                    b.HasOne("ApartmanApp.Core.Entities.Blok", "Blok")
                        .WithMany("Daireler")
                        .HasForeignKey("BlokId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Blok");
                });

            modelBuilder.Entity("ApartmanApp.Core.Entities.OtomatikAidat", b =>
                {
                    b.HasOne("ApartmanApp.Core.Entities.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("ApartmanApp.Core.Entities.Oylama", b =>
                {
                    b.HasOne("ApartmanApp.Core.Entities.Kullanici", "Olusturan")
                        .WithMany()
                        .HasForeignKey("OlusturanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Olusturan");
                });

            modelBuilder.Entity("ApartmanApp.Core.Entities.OylamaOyu", b =>
                {
                    b.HasOne("ApartmanApp.Core.Entities.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApartmanApp.Core.Entities.Oylama", "Oylama")
                        .WithMany("Oylar")
                        .HasForeignKey("OylamaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApartmanApp.Core.Entities.OylamaSecenek", "Secenek")
                        .WithMany("Oylar")
                        .HasForeignKey("SecenekId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kullanici");

                    b.Navigation("Oylama");

                    b.Navigation("Secenek");
                });

            modelBuilder.Entity("ApartmanApp.Core.Entities.OylamaSecenek", b =>
                {
                    b.HasOne("ApartmanApp.Core.Entities.Oylama", "Oylama")
                        .WithMany("Secenekler")
                        .HasForeignKey("OylamaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Oylama");
                });

            modelBuilder.Entity("ApartmanApp.Core.Entities.Ariza", b =>
                {
                    b.Navigation("Fotograflar");

                    b.Navigation("Takipler");
                });

            modelBuilder.Entity("ApartmanApp.Core.Entities.Blok", b =>
                {
                    b.Navigation("Daireler");
                });

            modelBuilder.Entity("ApartmanApp.Core.Entities.Kullanici", b =>
                {
                    b.Navigation("Arizalar");

                    b.Navigation("Takipler");
                });

            modelBuilder.Entity("ApartmanApp.Core.Entities.Oylama", b =>
                {
                    b.Navigation("Oylar");

                    b.Navigation("Secenekler");
                });

            modelBuilder.Entity("ApartmanApp.Core.Entities.OylamaSecenek", b =>
                {
                    b.Navigation("Oylar");
                });
#pragma warning restore 612, 618
        }
    }
}
